insert_buffer [get_pins I_PCI_TOP/U262/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U262/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/HFSBUF_179_1121/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/HFSBUF_179_1121/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/Y] NBUFFX2_HVT
insert_buffer [get_pins U986/A] NBUFFX2_HVT
insert_buffer [get_pins U986/Y] NBUFFX2_HVT
insert_buffer [get_pins I_BLENDER_0/ropt_mt_inst_55487/A] NBUFFX2_HVT
insert_buffer [get_pins I_BLENDER_0/ropt_mt_inst_55487/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U464/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_mt_inst_55528/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_mt_inst_55528/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF19/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF19/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55547/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55547/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55546/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55546/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF23/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF23/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF24/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF24/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF2/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF2/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U127/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U127/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF15/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF15/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55548/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55548/Y] NBUFFX2_HVT
insert_buffer [get_pins I_CLOCKING/copt_h_inst_54927/A] NBUFFX2_HVT
insert_buffer [get_pins I_CLOCKING/copt_h_inst_54927/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/copt_h_inst_54919/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/copt_h_inst_54919/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55583/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55583/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF9/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF9/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U_1_PTECO_HOLD_BUF37/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U_1_PTECO_HOLD_BUF37/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/ropt_h_inst_55541/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/ropt_h_inst_55541/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54956/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54956/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54955/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54955/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55545/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/ropt_h_inst_55545/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF34/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF34/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54913/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54913/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF4/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF4/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF5/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF5/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/ropt_h_inst_55542/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/ropt_h_inst_55542/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U285/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U285/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF25/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF25/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF26/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF26/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54913/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54913/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF20/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF20/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF33/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF33/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U291/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U291/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF6/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF6/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF30/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF30/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54943/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54943/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF8/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF8/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF35/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF35/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF28/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF28/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7584/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7584/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF7/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF7/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U277/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U277/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF27/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF27/Y] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF29/A] NBUFFX2_HVT
insert_buffer [get_pins I_PCI_TOP/U_1_PTECO_HOLD_BUF29/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U11380/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U11380/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7587/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7587/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/ZBUF_2_inst_25862/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/ZBUF_2_inst_25862/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U284/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U284/Y] NBUFFX2_HVT
insert_buffer [get_pins I_CONTEXT_MEM/copt_h_inst_54991/A] NBUFFX2_HVT
insert_buffer [get_pins I_CONTEXT_MEM/copt_h_inst_54991/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U286/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U286/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/copt_h_inst_54889/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54910/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54910/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U78/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U78/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U85/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U85/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U282/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U282/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF11/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U_1_PTECO_HOLD_BUF11/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54946/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54946/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U9340/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U9340/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U12488/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U12488/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U202/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/U202/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54947/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54947/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/copt_h_inst_54911/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7591/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/U7591/Y] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U95/A] NBUFFX2_HVT
insert_buffer [get_pins I_RISC_CORE/U95/Y] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/ZBUF_2450_inst_55304/A] NBUFFX2_HVT
insert_buffer [get_pins I_SDRAM_TOP/I_SDRAM_IF/ZBUF_2450_inst_55304/Y] NBUFFX2_HVT
